name: listeo
version: 0.1.0.0
github: "gigobyte/Listeo"
license: MIT
author: "Stanislav Iliev"
maintainer: "s.iliev3@gmail.com"
copyright: "2018 Stanislav Iliev"

dependencies:
  - base >= 4.7 && < 5
  - protolude
  - scotty
  - aeson
  - mongoDB
  - wai-cors
  - http-types
  - text
  - time
  - bytestring
  - transformers
  - bcrypt

executables:
  listeo-exe:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - DeriveGeneric
  - NamedFieldPuns
  - DuplicateRecordFields
